app:
  name: spring-boot-redis-example
  port: 8080
  database:
    hostname: ${DB_HOST:0.0.0.0}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:postgres_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  redis:
    nodes: ${REDIS_NODES:localhost:6379,localhost:6380,localhost:6381}
    username: ${REDIS_USER:default}
    password: ${REDIS_PASSWORD:password}

spring:
  application:
    name: ${app.name}

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${app.database.hostname}:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  # Redis Configuration (Cluster Mode)
  data:
    redis:
      username: ${app.redis.username}
      password: ${app.redis.password}
      cluster:
        # Provide at least one or two nodes; Lettuce will discover the rest
        nodes: ${app.redis.nodes}
        max-redirects: 3
      lettuce:
        cluster:
          refresh:
            adaptive: true # Refresh cluster topology on node failures/failover
            period: 60s    # Periodic background refresh
        #            dynamic-refresh-sources: false # Forces use of the provided nodes list, If getting a "Connection Timed Out" during Redis operations
        pool:
          max-active: 100
          max-idle: 50
          min-idle: 10
          max-wait: 1000ms

  # Database Migration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: ${app.port}

# Logging Levels for Debugging
logging:
  level:
    root: INFO
    com.eric6166: DEBUG
    org.springframework.data.redis: INFO
    org.apache.http: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.sql: DEBUG # Optional: To see SQL queries if using JPA elsewhere
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE # log input parameter
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"